name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://www.scriptysphere.org/
            https://www.scriptysphere.org/about
            https://www.scriptysphere.org/programs
          uploadArtifacts: true
          temporaryPublicStorage: true
